### PR TITLE
A copy of fax_waveform in python

### PR DESCRIPTION
**Pull request by zhut19**
As suggested by @jhowl01, it's better leaving the original fax_waveform intact and make a separate folder for this alternative frame.

### CODE REVIEW

**Comment by jhowl01** [comment]
This is an extension/reopening of #40, for the record.

**Comment by tunnell** [comment]
Interesting.  Is this to split fax outside of pax?  Also, maybe @JelleAalbers interested since this may be useful for nT.

**Comment by jhowl01** [comment]
To briefly review the history for posterity (to the extent I know it 😄) : 

Qing built the set of scripts in [this directory](https://github.com/XENON1T/processing/tree/master/montecarlo/fax_waveform) a couple years back, mainly since his study of reconstruction bias required large statistics of waveform-simulated S1s/S2s, without much regard for the spectra. 

@pdeperio also used/uses some of the code in this dir in the [full MC chain](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L401), to get the "truth info" from the fax instruction file into the same dataframe as the hax output.

@zhut19 made the code much simpler and removed all the bash calling, so now it is very simple to efficiently generate large statistics on compute nodes.

The framework is very useful for getting fax data if too much stats are required to directly `run()` pax in your notebook, and if you want to compare instructions to reconstructed information.

**Comment by tunnell** [comment]
Ah, but it's still fax, just wrapped a lot. 

@jpienaar13  we should think for nT how all of this fits together between MC, strax, etc

**Comment by pdeperio** [comment]
The output of fax truth info in full chain [here](https://github.com/XENON1T/processing/blob/master/montecarlo/run_sim.sh#L404) is very slow in Pythonic analysis. This framework is a first step towards improving this, but will need to be revisited later in case of any more complicated truth-peak to reconstructed-peak matching analysis.

**Pull request merged**
